import "./globals.css";
import type { Metadata } from "next";
import NextuiProvider from "@/components/Providers/NextUIProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
// import Footer from "@/components/Footer/Footer";
// import TradeInNavbar from "@/components/Navbar/Navbar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="eng">
      <title>TradeIn</title>
      <head>
        <link rel="shortcut icon" href="/logo.jpg" type="image/x-icon" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
          integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        />
      </head>
      <body className="max-w-[2000px] m-auto">
        <NextuiProvider>
          {children}
          <ToastContainer theme="dark" />
        </NextuiProvider>
      </body>
    </html>
  );
}
