import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Chakra from "@/components/Chakra";
import Home from "@/components/Home";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Chakra>
<<<<<<< HEAD
          <Navbar />
        <Sidebar />
=======
          <Home/>
>>>>>>> 5705e7a3f2f6d00d3d9ad657ebc5ed45a94fd829
        {children}
        </Chakra>
      </body>
    </html>
  );
}
