import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Chakra from "@/components/Chakra";
import Home from "@/components/Home";
import NextuiProvider from "@/components/NextUIProvider";
import TradeInNavbar from "@/components/Navbar";



// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="eng">
      <body className="">
       <NextuiProvider>
        {children}
       </NextuiProvider>
      </body>
    </html>
  );
}
